apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-analyzer
  template:
    metadata:
      labels:
        app: html-analyzer
    spec:
      containers:
        - name: html-analyzer
          image: your_registry/your_image_name
          ports:
            - containerPort: 8501
          env:
            - name: ENVIRONMENT_VARIABLE_NAME
              value: "value_here"
          resources:
            limits:
              cpu: "1" # maximum of 0.5 CPU cores
              memory: "512Mi" # maximum of 512 MB memory
